fix(webpack): bump to 5.61.0 to use OpenSSL3.0 valid algorithms
OpenSSL3.0 has made several legacy algorithms no longer usable by
default.

https://wiki.openssl.org/index.php/OpenSSL_3.0#Legacy_Algorithms

A user now gets errors of this form with newer node versions:

```
$ npm run start:dev

> frontend@0.4.0 start:dev
> webpack serve --progress --config webpack.dev.js --env DOMAIN=v2dev.opensourcebrain.org --env NAMESPACE=osb2dev --env NODE_OPTIONS='--max-old-space-size=12048'

/home/asinha/Documents/02_Code/00_mine/2020-OSB/osbv2/OSBv2/applications/osb-portal/public
{
  WEBPACK_SERVE: true,
  DOMAIN: 'v2dev.opensourcebrain.org',
  NAMESPACE: 'osb2dev',
  NODE_OPTIONS: '--max-old-space-size=12048'
}
1% setup initialize(node:2976510) [DEP_WEBPACK_DEV_SERVER_CONSTRUCTOR] DeprecationWarning: Using 'compiler' as the first argument is deprecated. Please use 'options' as the first argument and 'compiler' as the second argument.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:2976510) [DEP_WEBPACK_DEV_SERVER_LISTEN] DeprecationWarning: 'listen' is deprecated. Please use async 'start' or 'startCallback' methods.
(node:2976510) [DEP_WEBPACK_DEV_SERVER_HTTPS] DeprecationWarning: 'https' option is deprecated. Please use the 'server' option.
<i> [webpack-dev-server] Generating SSL certificate...
<i> [webpack-dev-server] SSL certificate: /home/asinha/Documents/02_Code/00_mine/2020-OSB/osbv2/OSBv2/applications/osb-portal/node_modules/.cache/webpack-dev-server/server.pem
<i> [webpack-dev-server] [HPM] Proxy created: /proxy/workspaces  -> https://workspaces.v2dev.opensourcebrain.org/
<i> [webpack-dev-server] [HPM] Proxy rewrite rule created: "^/proxy/workspaces" ~> ""
<i> [webpack-dev-server] [HPM] Proxy created: /proxy/accounts-api  -> https://api.accounts.v2dev.opensourcebrain.org/
<i> [webpack-dev-server] [HPM] Proxy rewrite rule created: "^/proxy/accounts-api" ~> ""
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: https://localhost:3000/
<i> [webpack-dev-server] On Your Network (IPv4): https://192.168.1.180:3000/
<i> [webpack-dev-server] On Your Network (IPv6): https://[fe80::e960:e509:d3dd:e65a]:3000/
<i> [webpack-dev-server] Content not from webpack is served from '/home/asinha/Documents/02_Code/00_mine/2020-OSB/osbv2/OSBv2/applications/osb-portal/public' directory
<i> [webpack-dev-server] 404s will fallback to '/index.html'
10% building 0/3 entries 3/3 dependencies 0/3 modulesnode:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/home/asinha/Documents/02_Code/00_mine/2020-OSB/osbv2/OSBv2/applications/osb-portal/node_modules/webpack/lib/util/createHash.js:144:18)
    at BulkUpdateDecorator.update (/home/asinha/Documents/02_Code/00_mine/2020-OSB/osbv2/OSBv2/applications/osb-portal/node_modules/webpack/lib/util/createHash.js:46:50)
    at OriginalSource.updateHash (/home/asinha/Documents/02_Code/00_mine/2020-OSB/osbv2/OSBv2/applications/osb-portal/node_modules/webpack-sources/lib/OriginalSource.js:104:8)
    at NormalModule._initBuildHash (/home/asinha/Documents/02_Code/00_mine/2020-OSB/osbv2/OSBv2/applications/osb-portal/node_modules/webpack/lib/NormalModule.js:839:17)
    at handleParseResult (/home/asinha/Documents/02_Code/00_mine/2020-OSB/osbv2/OSBv2/applications/osb-portal/node_modules/webpack/lib/NormalModule.js:904:10)
    at /home/asinha/Documents/02_Code/00_mine/2020-OSB/osbv2/OSBv2/applications/osb-portal/node_modules/webpack/lib/NormalModule.js:995:4
    at processResult (/home/asinha/Documents/02_Code/00_mine/2020-OSB/osbv2/OSBv2/applications/osb-portal/node_modules/webpack/lib/NormalModule.js:718:11)
    at /home/asinha/Documents/02_Code/00_mine/2020-OSB/osbv2/OSBv2/applications/osb-portal/node_modules/webpack/lib/NormalModule.js:778:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

webpack was fixed to use valid OpenSSL3 algorithms in 5.61.0:
https://github.com/webpack/webpack/pull/14584/commits/dcf3b02aaf407f0fc07354b20af5413296a56e58

So bump the version to 5.61.0 in our repo here also.

Note, there are multiple posts on the internet about how to enable
legacy algorithms to "work around" this issue, but I don't think that's
the best way to go about it. If OpenSSL thinks there are insecure enough
to disable by default, it's best to follow them.